SKILL_RECOMMENDER_THRESHOLD_FOR_APPLICANT = 0.5
SKILLS_RECOMMENDER_THRESHOLD_FOR_ADVERTISEMENT = 0.5

SKILLS_RECOMMENDER_THRESHOLD_FOR_APPLICANT_l1 = 0.8
SKILLS_RECOMMENDER_THRESHOLD_FOR_ADVERTISEMENT_l1 = 0.8
SKILLS_RECOMMENDER_THRESHOLD_FOR_APPLICANT_l2 = 0.7
SKILLS_RECOMMENDER_THRESHOLD_FOR_ADVERTISEMENT_l2 = 0.7
SKILLS_RECOMMENDER_THRESHOLD_FOR_APPLICANT_l3 = 0.6
SKILLS_RECOMMENDER_THRESHOLD_FOR_ADVERTISEMENT_l3 = 0.6


JOB_POSITION_RECOMMENDER_THRESHOLD_FOR_ADVERTISEMENT = 0.6
JOB_POSITION_RECOMMENDER_THRESHOLD_FOR_APPLICANT = 0.6
JOB_CATEGORY_RECOMMENDER_THRESHOLD_FOR_APPLICANT = 0.7
JOB_CATEGORY_RECOMMENDER_THRESHOLD_FOR_ADVERTISEMENT = 0.7
WEIGHTED_THRESHOLD_FOR_NEW_ADVERTISEMENT = 0.65
WEIGHTED_THRESHOLD_FOR_NEW_APPLICANT = 0.6

AD_ENGINE = {
    "primary":["description","title"],

}

AP_ENGINE = {
    "primary":["about_me","past_experiences","education_qualifications","licences_certifications"]

}
